# Site settings
title: 痞子丶蔡的架构师之路 
motto: 道可道，非常道。名可名，非常名。无名天地之始。有名万物之母。故常无欲以观其妙。
email: heylear@126.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://heylear.github.io" # the base hostname & protocol for your site
twitter_username: heylear 
github_username: heylear 

# Build settings
markdown: kramdown
